import type {DMMF, GeneratorOptions} from '@prisma/generator-helper';
import * as fs from 'fs/promises';
import {
  beforeEach,
  describe,
  expect,
  it,
  vi,
  type MockedFunction,
} from 'vitest';
import {onGenerate} from '../src/generator';
import {createEnum, createField, createMockDMMF, createModel} from './utils';

// Mock fs/promises
vi.mock('fs/promises', () => ({
  writeFile: vi.fn(),
  mkdir: vi.fn(),
  readFile: vi.fn(),
}));

function createTestOptions(dmmf: DMMF.Document): GeneratorOptions {
  return {
    generator: {
      output: {value: 'generated', fromEnvVar: null},
      name: 'test-generator',
      config: {},
      provider: {value: 'test-provider', fromEnvVar: null},
      binaryTargets: [],
      previewFeatures: [],
      sourceFilePath: '',
    },
    dmmf,
    schemaPath: '',
    datasources: [],
    otherGenerators: [],
    version: '0.0.0',
    datamodel: '',
  };
}

describe('Generator', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('Schema Generation', () => {
    it('should generate correct schema for basic model', async () => {
      const mockModel: DMMF.Model = {
        name: 'User',
        dbName: null,
        schema: null,
        fields: [
          createField('id', 'String', {isId: true}),
          createField('name', 'String'),
          createField('email', 'String'),
          createField('age', 'Int', {isRequired: false}),
        ],
        uniqueFields: [],
        uniqueIndexes: [],
        primaryKey: null,
      };

      await onGenerate(createTestOptions(createMockDMMF([mockModel])));

      // Verify mkdir was called
      expect(fs.mkdir).toHaveBeenCalledWith('generated', {recursive: true});

      // Verify writeFile was called with correct schema
      const writeFileCalls = vi.mocked(fs.writeFile).mock.calls;
      expect(writeFileCalls.length).toBe(1);

      const content = getWrittenContent(writeFileCalls);

      expect(content).toMatchInlineSnapshot(`
        "// This file was automatically generated by prisma-zero.
        // You should NOT make any changes in this file as it will be overwritten.

        import {
          createBuilder,
          createSchema,
          number,
          string,
          table,
        } from "@rocicorp/zero";

        export const userTable = table("User")
          .columns({
            id: string(),
            name: string(),
            email: string(),
            age: number().optional(),
          })
          .primaryKey("id");

        /**
         * The Zero schema object.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const schema = createSchema({
          tables: [
            userTable,
          ],
        });

        /**
         * Represents the Zero schema type.
         * This type is auto-generated from your Prisma schema definition.
         */
        export type Schema = typeof schema;
        /**
         * Represents the ZQL query builder.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const zql = createBuilder(schema);
        /**
         * Represents the Zero schema query builder.
         * This type is auto-generated from your Prisma schema definition.
         *
         * @deprecated Use \`zql\` instead.
         */
        export const builder = zql;
        /** Defines the default types for Zero */
        declare module "@rocicorp/zero" {
          interface DefaultTypes {
            schema: Schema;
          }
        }
        "
      `);
    });

    it('should handle enums correctly', async () => {
      const mockEnum: DMMF.DatamodelEnum = {
        name: 'Role',
        values: [
          {name: 'USER', dbName: null},
          {name: 'ADMIN', dbName: null},
        ],
        dbName: null,
      };

      const mockModel: DMMF.Model = {
        name: 'User',
        dbName: null,
        schema: null,
        fields: [
          createField('id', 'String', {isId: true}),
          createField('role', 'Role', {kind: 'enum'}),
        ],
        uniqueFields: [],
        uniqueIndexes: [],
        primaryKey: null,
      };

      const options = createTestOptions(
        createMockDMMF([mockModel], [mockEnum]),
      );

      await onGenerate(options);

      const content = getWrittenContent(vi.mocked(fs.writeFile).mock.calls);

      expect(content).toMatchInlineSnapshot(`
        "// This file was automatically generated by prisma-zero.
        // You should NOT make any changes in this file as it will be overwritten.

        import {
          createBuilder,
          createSchema,
          enumeration,
          string,
          table,
        } from "@rocicorp/zero";

        export type Role = "USER" | "ADMIN";

        export const userTable = table("User")
          .columns({
            id: string(),
            role: enumeration<Role>(),
          })
          .primaryKey("id");

        /**
         * The Zero schema object.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const schema = createSchema({
          tables: [
            userTable,
          ],
        });

        /**
         * Represents the Zero schema type.
         * This type is auto-generated from your Prisma schema definition.
         */
        export type Schema = typeof schema;
        /**
         * Represents the ZQL query builder.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const zql = createBuilder(schema);
        /**
         * Represents the Zero schema query builder.
         * This type is auto-generated from your Prisma schema definition.
         *
         * @deprecated Use \`zql\` instead.
         */
        export const builder = zql;
        /** Defines the default types for Zero */
        declare module "@rocicorp/zero" {
          interface DefaultTypes {
            schema: Schema;
          }
        }
        "
      `);
    });

    it('should handle relationships correctly', async () => {
      // Create User model with a one-to-many relationship to Post
      const userModel = createModel('User', [
        createField('id', 'String', {isId: true}),
        createField('name', 'String'),
        createField('posts', 'Post', {
          kind: 'object',
          isList: true,
          relationName: 'UserPosts',
          relationToFields: ['id'],
          relationFromFields: ['userId'],
        }),
      ]);

      // Create Post model with both the foreign key and the relation field
      const postModel = createModel('Post', [
        createField('id', 'String', {isId: true}),
        createField('title', 'String'),
        createField('userId', 'String'),
        createField('user', 'User', {
          kind: 'object',
          relationName: 'UserPosts',
          relationFromFields: ['userId'],
          relationToFields: ['id'],
        }),
      ]);

      await onGenerate(
        createTestOptions(createMockDMMF([userModel, postModel])),
      );

      const content = getWrittenContent(vi.mocked(fs.writeFile).mock.calls);

      // Verify the generated code contains the relationship definitions
      expect(content).toMatchInlineSnapshot(`
        "// This file was automatically generated by prisma-zero.
        // You should NOT make any changes in this file as it will be overwritten.

        import {
          createBuilder,
          createSchema,
          relationships,
          string,
          table,
        } from "@rocicorp/zero";

        export const userTable = table("User")
          .columns({
            id: string(),
            name: string(),
          })
          .primaryKey("id");

        export const postTable = table("Post")
          .columns({
            id: string(),
            title: string(),
            userId: string(),
          })
          .primaryKey("id");

        export const userTableRelationships = relationships(userTable, ({ many }) => ({
          posts: many({
            sourceField: ["id"],
            destField: ["userId"],
            destSchema: postTable,
          })
        }));
        export const postTableRelationships = relationships(postTable, ({ one }) => ({
          user: one({
            sourceField: ["userId"],
            destField: ["id"],
            destSchema: userTable,
          })
        }));
        /**
         * The Zero schema object.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const schema = createSchema({
          tables: [
            userTable,
            postTable,
          ],
          relationships: [
            userTableRelationships,
            postTableRelationships,
          ],
        });

        /**
         * Represents the Zero schema type.
         * This type is auto-generated from your Prisma schema definition.
         */
        export type Schema = typeof schema;
        /**
         * Represents the ZQL query builder.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const zql = createBuilder(schema);
        /**
         * Represents the Zero schema query builder.
         * This type is auto-generated from your Prisma schema definition.
         *
         * @deprecated Use \`zql\` instead.
         */
        export const builder = zql;
        /** Defines the default types for Zero */
        declare module "@rocicorp/zero" {
          interface DefaultTypes {
            schema: Schema;
          }
        }
        "
      `);
    });

    it('should generate correct schema for model with @map attributes', async () => {
      const messageModel = createModel('message', [
        createField('id', 'String', {isId: true, dbName: null}), // No @map
        createField('senderID', 'String', {
          isRequired: false,
          dbName: 'sender_id', // @map("sender_id")
        }),
        createField('mediumID', 'String', {
          isRequired: false,
          dbName: 'medium_id', // @map("medium_id")
        }),
      ]);

      await onGenerate(createTestOptions(createMockDMMF([messageModel])));

      const content = getWrittenContent(vi.mocked(fs.writeFile).mock.calls);

      // Verify the output includes .from() calls for mapped columns
      expect(content).toContain(
        "senderID: string().from('sender_id').optional()",
      );
      expect(content).toContain(
        "mediumID: string().from('medium_id').optional()",
      );
    });
  });

  describe('Many-to-Many Relationships', () => {
    it('should generate correct schema for implicit many-to-many relationship', async () => {
      // Create Post model with categories relationship
      const postModel = createModel('Post', [
        createField('id', 'Int', {isId: true}),
        createField('title', 'String'),
        createField('categories', 'Category', {
          isList: true,
          relationName: 'PostToCategory',
          kind: 'object',
        }),
      ]);

      // Create Category model with posts relationship
      const categoryModel = createModel('Category', [
        createField('id', 'Int', {isId: true}),
        createField('name', 'String'),
        createField('posts', 'Post', {
          isList: true,
          relationName: 'PostToCategory',
          kind: 'object',
        }),
      ]);

      const dmmf = createMockDMMF([postModel, categoryModel]);
      const options = createTestOptions(dmmf);

      // Mock readFile to return null (no existing schema)
      vi.mocked(fs.readFile).mockRejectedValue(new Error('File not found'));

      await onGenerate(options);

      const content = getWrittenContent(vi.mocked(fs.writeFile).mock.calls);
      expect(content).toMatchInlineSnapshot(`
        "// This file was automatically generated by prisma-zero.
        // You should NOT make any changes in this file as it will be overwritten.

        import {
          createBuilder,
          createSchema,
          number,
          relationships,
          string,
          table,
        } from "@rocicorp/zero";

        export const postTable = table("Post")
          .columns({
            id: number(),
            title: string(),
          })
          .primaryKey("id");

        export const categoryTable = table("Category")
          .columns({
            id: number(),
            name: string(),
          })
          .primaryKey("id");

        export const _postToCategoryTable = table("_PostToCategory")
          .from("_PostToCategory")
          .columns({
            A: number(),
            B: number(),
          })
          .primaryKey("A", "B");

        export const postTableRelationships = relationships(postTable, ({ many }) => ({
          categories: many({
            sourceField: ["id"],
            destField: ["B"],
            destSchema: _postToCategoryTable,
          }, {
            sourceField: ["A"],
            destField: ["id"],
            destSchema: categoryTable,
          })
        }));
        export const categoryTableRelationships = relationships(categoryTable, ({ many }) => ({
          posts: many({
            sourceField: ["id"],
            destField: ["A"],
            destSchema: _postToCategoryTable,
          }, {
            sourceField: ["B"],
            destField: ["id"],
            destSchema: postTable,
          })
        }));
        export const _postToCategoryTableRelationships = relationships(_postToCategoryTable, ({ one }) => ({
          modelA: one({
            sourceField: ["A"],
            destField: ["id"],
            destSchema: categoryTable,
          }),
          modelB: one({
            sourceField: ["B"],
            destField: ["id"],
            destSchema: postTable,
          })
        }));
        /**
         * The Zero schema object.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const schema = createSchema({
          tables: [
            postTable,
            categoryTable,
            _postToCategoryTable,
          ],
          relationships: [
            postTableRelationships,
            categoryTableRelationships,
            _postToCategoryTableRelationships,
          ],
        });

        /**
         * Represents the Zero schema type.
         * This type is auto-generated from your Prisma schema definition.
         */
        export type Schema = typeof schema;
        /**
         * Represents the ZQL query builder.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const zql = createBuilder(schema);
        /**
         * Represents the Zero schema query builder.
         * This type is auto-generated from your Prisma schema definition.
         *
         * @deprecated Use \`zql\` instead.
         */
        export const builder = zql;
        /** Defines the default types for Zero */
        declare module "@rocicorp/zero" {
          interface DefaultTypes {
            schema: Schema;
          }
        }
        "
      `);
    });

    it('should use custom relation name for implicit many-to-many table', async () => {
      // Create Post model with categories relationship using custom relation name
      const postModel = createModel('Post', [
        createField('id', 'Int', {isId: true}),
        createField('title', 'String'),
        createField('categories', 'Category', {
          isList: true,
          relationName: 'MyCustomRelation',
          kind: 'object',
        }),
      ]);

      // Create Category model with posts relationship
      const categoryModel = createModel('Category', [
        createField('id', 'Int', {isId: true}),
        createField('name', 'String'),
        createField('posts', 'Post', {
          isList: true,
          relationName: 'MyCustomRelation',
          kind: 'object',
        }),
      ]);

      const dmmf = createMockDMMF([postModel, categoryModel]);
      const options = createTestOptions(dmmf);

      // Mock readFile to return null (no existing schema)
      vi.mocked(fs.readFile).mockRejectedValue(new Error('File not found'));

      await onGenerate(options);

      const content = getWrittenContent(vi.mocked(fs.writeFile).mock.calls);
      expect(content).toMatchInlineSnapshot(`
        "// This file was automatically generated by prisma-zero.
        // You should NOT make any changes in this file as it will be overwritten.

        import {
          createBuilder,
          createSchema,
          number,
          relationships,
          string,
          table,
        } from "@rocicorp/zero";

        export const postTable = table("Post")
          .columns({
            id: number(),
            title: string(),
          })
          .primaryKey("id");

        export const categoryTable = table("Category")
          .columns({
            id: number(),
            name: string(),
          })
          .primaryKey("id");

        export const _myCustomRelationTable = table("_MyCustomRelation")
          .from("_MyCustomRelation")
          .columns({
            A: number(),
            B: number(),
          })
          .primaryKey("A", "B");

        export const postTableRelationships = relationships(postTable, ({ many }) => ({
          categories: many({
            sourceField: ["id"],
            destField: ["B"],
            destSchema: _myCustomRelationTable,
          }, {
            sourceField: ["A"],
            destField: ["id"],
            destSchema: categoryTable,
          })
        }));
        export const categoryTableRelationships = relationships(categoryTable, ({ many }) => ({
          posts: many({
            sourceField: ["id"],
            destField: ["A"],
            destSchema: _myCustomRelationTable,
          }, {
            sourceField: ["B"],
            destField: ["id"],
            destSchema: postTable,
          })
        }));
        export const _myCustomRelationTableRelationships = relationships(_myCustomRelationTable, ({ one }) => ({
          modelA: one({
            sourceField: ["A"],
            destField: ["id"],
            destSchema: categoryTable,
          }),
          modelB: one({
            sourceField: ["B"],
            destField: ["id"],
            destSchema: postTable,
          })
        }));
        /**
         * The Zero schema object.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const schema = createSchema({
          tables: [
            postTable,
            categoryTable,
            _myCustomRelationTable,
          ],
          relationships: [
            postTableRelationships,
            categoryTableRelationships,
            _myCustomRelationTableRelationships,
          ],
        });

        /**
         * Represents the Zero schema type.
         * This type is auto-generated from your Prisma schema definition.
         */
        export type Schema = typeof schema;
        /**
         * Represents the ZQL query builder.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const zql = createBuilder(schema);
        /**
         * Represents the Zero schema query builder.
         * This type is auto-generated from your Prisma schema definition.
         *
         * @deprecated Use \`zql\` instead.
         */
        export const builder = zql;
        /** Defines the default types for Zero */
        declare module "@rocicorp/zero" {
          interface DefaultTypes {
            schema: Schema;
          }
        }
        "
      `);
    });

    it('should handle array fields correctly', async () => {
      const userModel = createModel('User', [
        createField('id', 'String', {isId: true}),
        createField('email', 'String'),
        createField('tags', 'String', {isList: true}),
        createField('scores', 'Int', {isList: true, isRequired: false}),
        createField('features', 'Json', {isList: true}),
      ]);

      const options = createTestOptions(createMockDMMF([userModel]));

      // Mock readFile to return null (no existing schema)
      vi.mocked(fs.readFile).mockRejectedValue(new Error('File not found'));

      await onGenerate(options);

      const content = getWrittenContent(vi.mocked(fs.writeFile).mock.calls);
      expect(content).toMatchInlineSnapshot(`
        "// This file was automatically generated by prisma-zero.
        // You should NOT make any changes in this file as it will be overwritten.

        import {
          createBuilder,
          createSchema,
          json,
          string,
          table,
        } from "@rocicorp/zero";

        export const userTable = table("User")
          .columns({
            id: string(),
            email: string(),
            tags: json<string[]>(),
            scores: json<number[]>().optional(),
            features: json<any[]>(),
          })
          .primaryKey("id");

        /**
         * The Zero schema object.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const schema = createSchema({
          tables: [
            userTable,
          ],
        });

        /**
         * Represents the Zero schema type.
         * This type is auto-generated from your Prisma schema definition.
         */
        export type Schema = typeof schema;
        /**
         * Represents the ZQL query builder.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const zql = createBuilder(schema);
        /**
         * Represents the Zero schema query builder.
         * This type is auto-generated from your Prisma schema definition.
         *
         * @deprecated Use \`zql\` instead.
         */
        export const builder = zql;
        /** Defines the default types for Zero */
        declare module "@rocicorp/zero" {
          interface DefaultTypes {
            schema: Schema;
          }
        }
        "
      `);
    });

    it('should handle array fields with enums correctly', async () => {
      const statusEnum = createEnum('Status', [
        'ACTIVE',
        'INACTIVE',
        'PENDING',
      ]);

      const productModel = createModel('Product', [
        createField('id', 'String', {isId: true}),
        createField('name', 'String'),
        createField('statuses', 'Status', {kind: 'enum', isList: true}),
      ]);

      const options = createTestOptions(
        createMockDMMF([productModel], [statusEnum]),
      );

      // Mock readFile to return null (no existing schema)
      vi.mocked(fs.readFile).mockRejectedValue(new Error('File not found'));

      await onGenerate(options);

      const content = getWrittenContent(vi.mocked(fs.writeFile).mock.calls);
      expect(content).toMatchInlineSnapshot(`
        "// This file was automatically generated by prisma-zero.
        // You should NOT make any changes in this file as it will be overwritten.

        import {
          createBuilder,
          createSchema,
          json,
          string,
          table,
        } from "@rocicorp/zero";

        export type Status = "ACTIVE" | "INACTIVE" | "PENDING";

        export const productTable = table("Product")
          .columns({
            id: string(),
            name: string(),
            statuses: json<Status[]>(),
          })
          .primaryKey("id");

        /**
         * The Zero schema object.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const schema = createSchema({
          tables: [
            productTable,
          ],
        });

        /**
         * Represents the Zero schema type.
         * This type is auto-generated from your Prisma schema definition.
         */
        export type Schema = typeof schema;
        /**
         * Represents the ZQL query builder.
         * This type is auto-generated from your Prisma schema definition.
         */
        export const zql = createBuilder(schema);
        /**
         * Represents the Zero schema query builder.
         * This type is auto-generated from your Prisma schema definition.
         *
         * @deprecated Use \`zql\` instead.
         */
        export const builder = zql;
        /** Defines the default types for Zero */
        declare module "@rocicorp/zero" {
          interface DefaultTypes {
            schema: Schema;
          }
        }
        "
      `);
    });
  });
});

function getWrittenContent(
  writeFileCalls: MockedFunction<typeof fs.writeFile>['mock']['calls'],
) {
  const [, contentBuffer] = writeFileCalls[0] ?? [undefined, undefined];
  return contentBuffer?.toString();
}
